
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 5;
  public static final int MOD = 7;
  public static final int LT = 11;
  public static final int SIN = 13;
  public static final int PLUS = 3;
  public static final int RPAREN = 18;
  public static final int COS = 14;
  public static final int LN = 9;
  public static final int SQRT = 12;
  public static final int LPAREN = 17;
  public static final int ENTER = 2;
  public static final int LOG = 10;
  public static final int EXPO = 8;
  public static final int COMMA = 19;
  public static final int NUMBER = 20;
  public static final int EOF = 0;
  public static final int DIVIDE = 6;
  public static final int MINUS = 4;
  public static final int error = 1;
  public static final int TAN = 15;
  public static final int UMINUS = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ENTER",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "MOD",
  "EXPO",
  "LN",
  "LOG",
  "LT",
  "SQRT",
  "SIN",
  "COS",
  "TAN",
  "UMINUS",
  "LPAREN",
  "RPAREN",
  "COMMA",
  "NUMBER"
  };
}

